# Generated by Django 4.0.8 on 2022-10-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_remove_category_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='ADMIN.category'),
        ),
    ]
