# Generated by Django 4.0.8 on 2022-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0005_delete_subcategory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(to='ADMIN.category'),
        ),
    ]
