# Generated by Django 4.0.8 on 2022-11-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0008_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ADMIN.brand'),
        ),
    ]
