# Generated by Django 4.0.8 on 2022-10-11 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
