# Generated by Django 4.0.8 on 2022-10-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_accounts_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='uid',
        ),
    ]
