# Generated by Django 4.0.8 on 2022-10-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0013_address_alter_accounts_uid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincart',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='USER.order'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000285775D4A60>', max_length=200),
        ),
    ]
