# Generated by Django 4.0.8 on 2022-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0014_admincart_order_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001F169CD4A60>', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Order Confirmed', max_length=100),
        ),
    ]
