# Generated by Django 4.0.8 on 2022-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0015_alter_accounts_uid_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000013A6D2D8A60>', max_length=200),
        ),
    ]
