# Generated by Django 4.0.8 on 2022-11-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0016_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001BCBCAD4A60>', max_length=200),
        ),
    ]
