# Generated by Django 4.0.8 on 2022-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0017_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000015D089F4A60>', max_length=200),
        ),
    ]
