# Generated by Django 4.0.8 on 2022-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0018_usercart_cancel_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='price_with_offer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001E759DD4A60>', max_length=200),
        ),
    ]
