# Generated by Django 4.0.8 on 2022-11-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0019_usercart_price_with_offer_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000024339CBF370>', max_length=200),
        ),
    ]
