# Generated by Django 4.0.8 on 2022-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0024_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001D1425643A0>', max_length=200),
        ),
    ]
